[functions."rebuild"]
schedule = "@hourly"

[[headers]]
  for = "/api/"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/feed/"
  [headers.values]
    Content-Type = "application/rss+xml"
